2017-03-27 23:22:27 database: wrong user or password; user: "ARTEM"
org.h2.message.DbException: Неверное имя пользователя или пароль
Wrong user name or password [28000-194]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:104)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:947)
	at org.h2.server.web.WebApp.process(WebApp.java:210)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Неверное имя пользователя или пароль
Wrong user name or password [28000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2017-03-27 23:22:33 database: wrong user or password; user: "ARTEM"
org.h2.message.DbException: Неверное имя пользователя или пароль
Wrong user name or password [28000-194]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:104)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:947)
	at org.h2.server.web.WebApp.process(WebApp.java:210)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Неверное имя пользователя или пароль
Wrong user name or password [28000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2017-03-28 00:16:25 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Таблица "TEST" не найдена
Table "TEST" not found; SQL statement:
INSERT INTO TEST VALUES('a', 1, 'READ') [42102-194]
2017-03-28 00:16:25 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Таблица "TEST" не найдена
Table "TEST" not found; SQL statement:
INSERT INTO TEST VALUES('a.b', 1,'WRITE') [42102-194]
2017-03-28 00:25:22 database: wrong user or password; user: "ARTEM"
org.h2.message.DbException: Неверное имя пользователя или пароль
Wrong user name or password [28000-194]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:104)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:947)
	at org.h2.server.web.WebApp.process(WebApp.java:210)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Неверное имя пользователя или пароль
Wrong user name or password [28000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2017-03-28 00:25:24 database: wrong user or password; user: "ARTEM"
org.h2.message.DbException: Неверное имя пользователя или пароль
Wrong user name or password [28000-194]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:104)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:947)
	at org.h2.server.web.WebApp.process(WebApp.java:210)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Неверное имя пользователя или пароль
Wrong user name or password [28000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2017-03-28 00:43:52 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER VALUES (NAME AS[*] 'newUser') "; ожидалось "., (, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"
Syntax error in SQL statement "INSERT INTO USER VALUES (NAME AS[*] 'newUser') "; expected "., (, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
insert into user values (name as 'newUser') [42001-194]
2017-03-28 00:44:32 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество столбцов
Column count does not match; SQL statement:
insert into user values ('newUser','','') [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-28 00:44:42 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER VALUES (,[*]'newUser','','') "; ожидалось "), DEFAULT, NOT, EXISTS, INTERSECTS, SELECT, FROM, WITH"
Syntax error in SQL statement "INSERT INTO USER VALUES (,[*]'newUser','','') "; expected "), DEFAULT, NOT, EXISTS, INTERSECTS, SELECT, FROM, WITH"; SQL statement:
insert into user values (,'newUser','','') [42001-194]
2017-03-28 00:48:57 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество столбцов
Column count does not match; SQL statement:
insert into user values (11,ID ,'newUser','','') [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-28 00:55:35 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER NAME[*] SET 'dsfgh' "; ожидалось "., (, DIRECT, SORTED, DEFAULT, VALUES, SET, (, WITH, SELECT, FROM"
Syntax error in SQL statement "INSERT INTO USER NAME[*] SET 'dsfgh' "; expected "., (, DIRECT, SORTED, DEFAULT, VALUES, SET, (, WITH, SELECT, FROM"; SQL statement:
insert into user name set 'dsfgh' [42001-194]
2017-03-28 00:58:20 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ALTER COLUMN ID INT UNSIGNED AUTO_INCREMENT 10[*],1 "
Syntax error in SQL statement "ALTER TABLE USER ALTER COLUMN ID INT UNSIGNED AUTO_INCREMENT 10[*],1 "; SQL statement:
alter table user alter column id int UNSIGNED AUTO_INCREMENT 10,1 [42000-194]
2017-03-28 00:59:26 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ALTER COLUMN ID INT UNSIGNED AUTO_INCREMENT 10[*],1 "
Syntax error in SQL statement "ALTER TABLE USER ALTER COLUMN ID INT UNSIGNED AUTO_INCREMENT 10[*],1 "; SQL statement:
alter table user alter column id int UNSIGNED AUTO_INCREMENT 10,1 [42000-194]
2017-03-28 01:01:27 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "USER[*]"; ожидалось "UPDATE, USE, {"
Syntax error in SQL statement "USER[*]"; expected "UPDATE, USE, {"; SQL statement:
USER [42001-194]
2017-03-28 01:02:14 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER VALUES (,[*]'new','','') "; ожидалось "), DEFAULT, NOT, EXISTS, INTERSECTS, SELECT, FROM, WITH"
Syntax error in SQL statement "INSERT INTO USER VALUES (,[*]'new','','') "; expected "), DEFAULT, NOT, EXISTS, INTERSECTS, SELECT, FROM, WITH"; SQL statement:
insert into user values (,'new','','') [42001-194]
2017-03-28 01:02:29 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество столбцов
Column count does not match; SQL statement:
insert into user values ('new') [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-28 01:03:42 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER (NAME, PASS) VALUES ([*]‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "
Syntax error in SQL statement "INSERT INTO USER (NAME, PASS) VALUES ([*]‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; SQL statement:
INSERT INTO user (name, pass) VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42000-194]
2017-03-28 01:04:01 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER(NAME, PASS) VALUES ([*]‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "
Syntax error in SQL statement "INSERT INTO USER(NAME, PASS) VALUES ([*]‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; SQL statement:
INSERT INTO USER(NAME, PASS) VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42000-194]
2017-03-28 01:04:09 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:48 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:49 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:49 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:49 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:50 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:50 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:50 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:51 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:51 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:51 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:52 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:52 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:53 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:53 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:53 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:54 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:04:54 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS') VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS') VALUES (‘значение_первого_столбца’,’значение_второго_столбца’) [42001-194]
2017-03-28 01:05:14 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO USER('NAME'[*], 'PASS',ID) VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’,NULL) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO USER('NAME'[*], 'PASS',ID) VALUES (‘ЗНАЧЕНИЕ_ПЕРВОГО_СТОЛБЦА’,’ЗНАЧЕНИЕ_ВТОРОГО_СТОЛБЦА’,NULL) "; expected "identifier"; SQL statement:
INSERT INTO USER('NAME', 'PASS',id) VALUES (‘значение_первого_столбца’,’значение_второго_столбца’,null) [42001-194]
2017-03-28 01:11:39 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "DROP COLUMN[*] ID FROM USER "; ожидалось "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"
Syntax error in SQL statement "DROP COLUMN[*] ID FROM USER "; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
drop column id from USER [42001-194]
2017-03-28 01:13:58 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ADD ID INT NOT NULL IDENTITY (1,1) PRIMARY[*] KEY "
Syntax error in SQL statement "ALTER TABLE USER ADD ID INT NOT NULL IDENTITY (1,1) PRIMARY[*] KEY "; SQL statement:
Alter table user ADD id int NOT NULL IDENTITY (1,1) primary key [42000-194]
2017-03-28 01:14:26 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ADD ID INT NOT NULL IDENTITY (1,1) PRIMARY[*] KEY "
Syntax error in SQL statement "ALTER TABLE USER ADD ID INT NOT NULL IDENTITY (1,1) PRIMARY[*] KEY "; SQL statement:
Alter table user ADD id int NOT NULL IDENTITY (1,1) PRIMARY KEY [42000-194]
2017-03-28 01:14:32 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ADD ID INT NOT NULL PRIMARY[*] KEY IDENTITY (1,1) "
Syntax error in SQL statement "ALTER TABLE USER ADD ID INT NOT NULL PRIMARY[*] KEY IDENTITY (1,1) "; SQL statement:
Alter table user ADD id int NOT NULL PRIMARY KEY IDENTITY (1,1) [42000-194]
2017-03-28 01:14:36 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ADD ID INT NOT NULL PRIMARY[*] KEY IDENTITY (1,1) "
Syntax error in SQL statement "ALTER TABLE USER ADD ID INT NOT NULL PRIMARY[*] KEY IDENTITY (1,1) "; SQL statement:
Alter table user ADD id int NOT NULL PRIMARY KEY IDENTITY (1,1) [42000-194]
2017-03-28 01:14:43 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ADD ID INT  PRIMARY[*] KEY NOT NULL IDENTITY (1,1) "
Syntax error in SQL statement "ALTER TABLE USER ADD ID INT  PRIMARY[*] KEY NOT NULL IDENTITY (1,1) "; SQL statement:
Alter table user ADD id int  PRIMARY KEY NOT NULL IDENTITY (1,1) [42000-194]
2017-03-28 01:18:13 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Неизвестный тип данных: "PRIMARY"
Unknown data type: "PRIMARY"; SQL statement:
alter table user alter column id primary key [50004-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4144)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3994)
	at org.h2.command.Parser.parseAlterTableAlterColumnType(Parser.java:5770)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5739)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-28 01:18:21 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ALTER COLUMN ID INT PRIMARY[*] KEY "
Syntax error in SQL statement "ALTER TABLE USER ALTER COLUMN ID INT PRIMARY[*] KEY "; SQL statement:
alter table user alter column id int primary key [42000-194]
2017-03-28 01:18:31 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ALTER COLUMN ID INT PRIMARY[*] KEY "
Syntax error in SQL statement "ALTER TABLE USER ALTER COLUMN ID INT PRIMARY[*] KEY "; SQL statement:
alter table user alter column id int PRIMARY KEY [42000-194]
2017-03-28 01:19:18 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ALTER COLUMN PRIMARY[*] KEY (ID) INT  NOT NULL IDENTITY (1,1) "; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE USER ALTER COLUMN PRIMARY[*] KEY (ID) INT  NOT NULL IDENTITY (1,1) "; expected "identifier"; SQL statement:
alter table user alter column PRIMARY KEY (id) int  NOT NULL IDENTITY (1,1) [42001-194]
2017-03-28 01:19:41 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ALTER COLUMN PRIMARY[*] KEY (ID) INT  IDENTITY (1,1) "; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE USER ALTER COLUMN PRIMARY[*] KEY (ID) INT  IDENTITY (1,1) "; expected "identifier"; SQL statement:
alter table user alter column PRIMARY KEY (id) int  IDENTITY (1,1) [42001-194]
2017-03-28 01:19:58 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ALTER COLUMN PRIMARY[*] KEY(ID) INT  IDENTITY (1,1) "; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE USER ALTER COLUMN PRIMARY[*] KEY(ID) INT  IDENTITY (1,1) "; expected "identifier"; SQL statement:
alter table user alter column PRIMARY KEY(id) int  IDENTITY (1,1) [42001-194]
2017-03-28 01:24:09 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "DELETE FROM RESOURCE BY ID[*]=5 "
Syntax error in SQL statement "DELETE FROM RESOURCE BY ID[*]=5 "; SQL statement:
delete from resource by id=5 [42000-194]
2017-03-28 01:32:22 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE RESOURCE FOREIGN[*] KEY (USER_ID) REFERENCES USER (ID) "; ожидалось "., ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"
Syntax error in SQL statement "ALTER TABLE RESOURCE FOREIGN[*] KEY (USER_ID) REFERENCES USER (ID) "; expected "., ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
alter table resource FOREIGN KEY (user_id) REFERENCES user (id) [42001-194]
2017-03-28 01:37:14 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "RESOURCE[*]"; ожидалось "ROLLBACK, REVOKE, RUNSCRIPT, RELEASE, REPLACE, {"
Syntax error in SQL statement "RESOURCE[*]"; expected "ROLLBACK, REVOKE, RUNSCRIPT, RELEASE, REPLACE, {"; SQL statement:
RESOURCE [42001-194]
2017-03-28 01:38:25 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Неизвестный тип данных: "PRIMARY"
Unknown data type: "PRIMARY"; SQL statement:
alter table resource alter column id primary key [50004-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4144)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3994)
	at org.h2.command.Parser.parseAlterTableAlterColumnType(Parser.java:5770)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5739)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-28 01:38:55 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Индекс "PRIMARY_KEY_" не найден
Index "PRIMARY_KEY_" not found; SQL statement:
ALTER TABLE resource DROP PRIMARY KEY [42112-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getPrimaryKey(Table.java:771)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5609)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-28 01:40:34 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Таблица "ИМЯ_ТАБЛИЦЫ_РОДИТЕЛЯ" не найдена
Table "ИМЯ_ТАБЛИЦЫ_РОДИТЕЛЯ" not found; SQL statement:
ALTER TABLE resource add FOREIGN KEY (USER_ID ) REFERENCES имя_таблицы_родителя (ID ) [42102-194]
2017-03-28 01:45:09 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "'' (USER: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6311A2F9_09AF_4A61_9CBA_D9A408E50B19) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6311A2F9_09AF_4A61_9CBA_D9A408E50B19)"
Data conversion error converting "'' (USER: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6311A2F9_09AF_4A61_9CBA_D9A408E50B19) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6311A2F9_09AF_4A61_9CBA_D9A408E50B19)"; SQL statement:
INSERT INTO "PUBLIC"."USER"("NAME","PASS","SALT","ID")VALUES(?,?,?,?) -- (?1, ?2, ?3, ?4) [22018-194]
2017-03-28 01:45:09 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "'' (USER: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6311A2F9_09AF_4A61_9CBA_D9A408E50B19) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6311A2F9_09AF_4A61_9CBA_D9A408E50B19)"
Data conversion error converting "'' (USER: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6311A2F9_09AF_4A61_9CBA_D9A408E50B19) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6311A2F9_09AF_4A61_9CBA_D9A408E50B19)"; SQL statement:
INSERT INTO "PUBLIC"."USER"("NAME","PASS","SALT","ID")VALUES(?,?,?,?) -- (?1, ?2, ?3, ?4) [22018-194]
2017-03-28 01:50:38 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE ACCOUNTING DROP FOREIGN KEY [*]"; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE ACCOUNTING DROP FOREIGN KEY [*]"; expected "identifier"; SQL statement:
ALTER TABLE ACCOUNTING drop FOREIGN KEY [42001-194]
2017-03-28 15:57:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "DELETE FROM USER WHERE ID=*[*] "; ожидалось "ALL, ANY, SOME, SELECT, FROM, WITH"
Syntax error in SQL statement "DELETE FROM USER WHERE ID=*[*] "; expected "ALL, ANY, SOME, SELECT, FROM, WITH"; SQL statement:
delete from user where id=* [42001-194]
2017-03-28 16:03:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALLERT[*] TABLE RESOURCE ADD FOREIGN KEY (USER_ID ) REFERENCES USER  (ID ) "; ожидалось "ALTER, ANALYZE, {"
Syntax error in SQL statement "ALLERT[*] TABLE RESOURCE ADD FOREIGN KEY (USER_ID ) REFERENCES USER  (ID ) "; expected "ALTER, ANALYZE, {"; SQL statement:
allert table RESOURCE add FOREIGN KEY (USER_ID ) REFERENCES USER  (ID ) [42001-194]
2017-03-29 21:04:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Невозможно преобразование строки "2000" в тип "DATE"
Cannot parse "DATE" constant "2000"; SQL statement:
insert into ACCOUNTING (DATE_START) values (2000-00-00) -- (2000) [22007-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:81)
	at org.h2.value.Value.convertTo(Value.java:929)
	at org.h2.table.Column.convert(Column.java:149)
	at org.h2.command.dml.Insert.insertRows(Insert.java:143)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 2000
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:313)
	at org.h2.value.ValueDate.parse(ValueDate.java:79)
	... 15 more
2017-03-29 21:04:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Невозможно преобразование строки "2000-00-00" в тип "DATE"
Cannot parse "DATE" constant "2000-00-00"; SQL statement:
insert into ACCOUNTING (DATE_START) values ('2000-00-00') -- ('2000-00-00') [22007-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:81)
	at org.h2.value.Value.convertTo(Value.java:929)
	at org.h2.table.Column.convert(Column.java:149)
	at org.h2.command.dml.Insert.insertRows(Insert.java:143)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 2000-0-0
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:319)
	at org.h2.value.ValueDate.parse(ValueDate.java:79)
	... 15 more
2017-03-29 21:05:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Невозможно преобразование строки "2000 00 00" в тип "DATE"
Cannot parse "DATE" constant "2000 00 00"; SQL statement:
insert into ACCOUNTING (DATE_START) values ('2000 00 00') -- ('2000 00 00') [22007-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:81)
	at org.h2.value.Value.convertTo(Value.java:929)
	at org.h2.table.Column.convert(Column.java:149)
	at org.h2.command.dml.Insert.insertRows(Insert.java:143)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 2000 00 00
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:313)
	at org.h2.value.ValueDate.parse(ValueDate.java:79)
	... 15 more
2017-03-29 21:05:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO ACCOUNTING (DATE_START) VALUES (2000 00[*] 00) "; ожидалось "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"
Syntax error in SQL statement "INSERT INTO ACCOUNTING (DATE_START) VALUES (2000 00[*] 00) "; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
insert into ACCOUNTING (DATE_START) values (2000 00 00) [42001-194]
2017-03-29 21:05:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Невозможно преобразование строки "2000" в тип "DATE"
Cannot parse "DATE" constant "2000"; SQL statement:
insert into ACCOUNTING (DATE_START) values (2000-00-00) -- (2000) [22007-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:81)
	at org.h2.value.Value.convertTo(Value.java:929)
	at org.h2.table.Column.convert(Column.java:149)
	at org.h2.command.dml.Insert.insertRows(Insert.java:143)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 2000
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:313)
	at org.h2.value.ValueDate.parse(ValueDate.java:79)
	... 15 more
2017-03-29 21:05:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO ACCOUNTING (DATE_START) VALUES (2000-00-00 00[*]:00:00) "; ожидалось "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"
Syntax error in SQL statement "INSERT INTO ACCOUNTING (DATE_START) VALUES (2000-00-00 00[*]:00:00) "; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
insert into ACCOUNTING (DATE_START) values (2000-00-00 00:00:00) [42001-194]
2017-03-29 21:06:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Невозможно преобразование строки "2000" в тип "DATE"
Cannot parse "DATE" constant "2000"; SQL statement:
insert into ACCOUNTING (DATE_START) values (2000-00-00) -- (2000) [22007-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:81)
	at org.h2.value.Value.convertTo(Value.java:929)
	at org.h2.table.Column.convert(Column.java:149)
	at org.h2.command.dml.Insert.insertRows(Insert.java:143)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 2000
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:313)
	at org.h2.value.ValueDate.parse(ValueDate.java:79)
	... 15 more
2017-03-29 21:09:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Невозможно преобразование строки "2000-00-00" в тип "DATE"
Cannot parse "DATE" constant "2000-00-00"; SQL statement:
insert into ACCOUNTING (DATE_START) values (DATE '2000-00-00') [22007-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:81)
	at org.h2.command.Parser.readTerm(Parser.java:2883)
	at org.h2.command.Parser.readFactor(Parser.java:2374)
	at org.h2.command.Parser.readSum(Parser.java:2361)
	at org.h2.command.Parser.readConcat(Parser.java:2331)
	at org.h2.command.Parser.readCondition(Parser.java:2166)
	at org.h2.command.Parser.readAnd(Parser.java:2138)
	at org.h2.command.Parser.readExpression(Parser.java:2130)
	at org.h2.command.Parser.parseInsert(Parser.java:1086)
	at org.h2.command.Parser.parsePrepared(Parser.java:415)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 2000-0-0
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:319)
	at org.h2.value.ValueDate.parse(ValueDate.java:79)
	... 24 more
2017-03-29 21:11:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO ACCOUNTING (DATE_START) VALUES (PARSEDATETIME '2000-00-00'[*]) "; ожидалось "., (, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"
Syntax error in SQL statement "INSERT INTO ACCOUNTING (DATE_START) VALUES (PARSEDATETIME '2000-00-00'[*]) "; expected "., (, [, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
insert into ACCOUNTING (DATE_START) values (PARSEDATETIME '2000-00-00') [42001-194]
2017-03-29 21:17:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество параметров для функции "PARSEDATETIME", ожидаемое количество: "2..4"
Invalid parameter count for "PARSEDATETIME", expected count: "2..4"; SQL statement:
insert into ACCOUNTING (DATE_START) values (PARSEDATETIME(2000-00-00)) [7001-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.expression.Function.checkParameterCount(Function.java:2262)
	at org.h2.expression.Function.doneWithParameters(Function.java:2277)
	at org.h2.command.Parser.readFunction(Parser.java:2681)
	at org.h2.command.Parser.readTerm(Parser.java:2860)
	at org.h2.command.Parser.readFactor(Parser.java:2374)
	at org.h2.command.Parser.readSum(Parser.java:2361)
	at org.h2.command.Parser.readConcat(Parser.java:2331)
	at org.h2.command.Parser.readCondition(Parser.java:2166)
	at org.h2.command.Parser.readAnd(Parser.java:2138)
	at org.h2.command.Parser.readExpression(Parser.java:2130)
	at org.h2.command.Parser.parseInsert(Parser.java:1086)
	at org.h2.command.Parser.parsePrepared(Parser.java:415)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-29 21:25:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество параметров для функции "FORMATDATETIME", ожидаемое количество: "2..4"
Invalid parameter count for "FORMATDATETIME", expected count: "2..4"; SQL statement:
insert into ACCOUNTING (DATE_START) values (FORMATDATETIME (2000-00-00)) [7001-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.expression.Function.checkParameterCount(Function.java:2262)
	at org.h2.expression.Function.doneWithParameters(Function.java:2277)
	at org.h2.command.Parser.readFunction(Parser.java:2681)
	at org.h2.command.Parser.readTerm(Parser.java:2860)
	at org.h2.command.Parser.readFactor(Parser.java:2374)
	at org.h2.command.Parser.readSum(Parser.java:2361)
	at org.h2.command.Parser.readConcat(Parser.java:2331)
	at org.h2.command.Parser.readCondition(Parser.java:2166)
	at org.h2.command.Parser.readAnd(Parser.java:2138)
	at org.h2.command.Parser.readExpression(Parser.java:2130)
	at org.h2.command.Parser.parseInsert(Parser.java:1086)
	at org.h2.command.Parser.parsePrepared(Parser.java:415)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-29 21:27:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество параметров для функции "PARSEDATETIME", ожидаемое количество: "2..4"
Invalid parameter count for "PARSEDATETIME", expected count: "2..4"; SQL statement:
insert into ACCOUNTING (DATE_START) values (PARSEDATETIME (2000-00-00)) [7001-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.expression.Function.checkParameterCount(Function.java:2262)
	at org.h2.expression.Function.doneWithParameters(Function.java:2277)
	at org.h2.command.Parser.readFunction(Parser.java:2681)
	at org.h2.command.Parser.readTerm(Parser.java:2860)
	at org.h2.command.Parser.readFactor(Parser.java:2374)
	at org.h2.command.Parser.readSum(Parser.java:2361)
	at org.h2.command.Parser.readConcat(Parser.java:2331)
	at org.h2.command.Parser.readCondition(Parser.java:2166)
	at org.h2.command.Parser.readAnd(Parser.java:2138)
	at org.h2.command.Parser.readExpression(Parser.java:2130)
	at org.h2.command.Parser.parseInsert(Parser.java:1086)
	at org.h2.command.Parser.parsePrepared(Parser.java:415)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-29 21:29:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Невозможно преобразование строки "2000" в тип "DATE"
Cannot parse "DATE" constant "2000"; SQL statement:
insert into ACCOUNTING (DATE_START) values (QUARTER (2000-00-00)) [22007-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:81)
	at org.h2.value.Value.convertTo(Value.java:929)
	at org.h2.value.Value.getDate(Value.java:409)
	at org.h2.expression.Function.getSimpleValue(Function.java:858)
	at org.h2.expression.Function.getValueWithArgs(Function.java:1195)
	at org.h2.expression.Function.getValue(Function.java:590)
	at org.h2.expression.Function.optimize(Function.java:2501)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 2000
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:313)
	at org.h2.value.ValueDate.parse(ValueDate.java:79)
	... 20 more
2017-03-29 21:31:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "PRINT[*] @DATE "; ожидалось "PREPARE, {"
Syntax error in SQL statement "PRINT[*] @DATE "; expected "PREPARE, {"; SQL statement:
PRINT @date [42001-194]
2017-03-29 21:32:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT [*]"; ожидалось "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
SHOW @date [42001-194]
2017-03-29 21:32:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT [*]"; ожидалось "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
SHOW (@date) [42001-194]
2017-03-29 21:33:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество параметров для функции "PARSEDATETIME", ожидаемое количество: "2..4"
Invalid parameter count for "PARSEDATETIME", expected count: "2..4"; SQL statement:
Set @date = PARSEDATETIME(2000-00-00) [7001-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.expression.Function.checkParameterCount(Function.java:2262)
	at org.h2.expression.Function.doneWithParameters(Function.java:2277)
	at org.h2.command.Parser.readFunction(Parser.java:2681)
	at org.h2.command.Parser.readTerm(Parser.java:2860)
	at org.h2.command.Parser.readFactor(Parser.java:2374)
	at org.h2.command.Parser.readSum(Parser.java:2361)
	at org.h2.command.Parser.readConcat(Parser.java:2331)
	at org.h2.command.Parser.readCondition(Parser.java:2166)
	at org.h2.command.Parser.readAnd(Parser.java:2138)
	at org.h2.command.Parser.readExpression(Parser.java:2130)
	at org.h2.command.Parser.parseSet(Parser.java:5093)
	at org.h2.command.Parser.parsePrepared(Parser.java:449)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-29 21:33:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество параметров для функции "PARSEDATETIME", ожидаемое количество: "2..4"
Invalid parameter count for "PARSEDATETIME", expected count: "2..4"; SQL statement:
Set @date = PARSEDATETIME(2000-00-00) [7001-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.expression.Function.checkParameterCount(Function.java:2262)
	at org.h2.expression.Function.doneWithParameters(Function.java:2277)
	at org.h2.command.Parser.readFunction(Parser.java:2681)
	at org.h2.command.Parser.readTerm(Parser.java:2860)
	at org.h2.command.Parser.readFactor(Parser.java:2374)
	at org.h2.command.Parser.readSum(Parser.java:2361)
	at org.h2.command.Parser.readConcat(Parser.java:2331)
	at org.h2.command.Parser.readCondition(Parser.java:2166)
	at org.h2.command.Parser.readAnd(Parser.java:2138)
	at org.h2.command.Parser.readExpression(Parser.java:2130)
	at org.h2.command.Parser.parseSet(Parser.java:5093)
	at org.h2.command.Parser.parsePrepared(Parser.java:449)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-29 21:33:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SET @DATE = PARSEDATETIME(2000-00-00,)[*] "; ожидалось "NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "SET @DATE = PARSEDATETIME(2000-00-00,)[*] "; expected "NOT, EXISTS, INTERSECTS"; SQL statement:
Set @date = PARSEDATETIME(2000-00-00,) [42001-194]
2017-03-29 21:36:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "YYYY" не найден
Column "YYYY" not found; SQL statement:
Set @date = PARSEDATETIME('2000-00-00',YYYY-MM-DD) [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:146)
	at org.h2.expression.Operation.optimize(Operation.java:181)
	at org.h2.expression.Operation.optimize(Operation.java:181)
	at org.h2.expression.Function.optimize(Function.java:2306)
	at org.h2.command.dml.Set.update(Set.java:463)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-29 21:37:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ACCOUNTING[*]"; ожидалось "ALTER, ANALYZE, {"
Syntax error in SQL statement "ACCOUNTING[*]"; expected "ALTER, ANALYZE, {"; SQL statement:
ACCOUNTING [42001-194]
2017-03-29 21:41:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "DELETE FROM ACCOUNTING  WHERE DATE_START =*[*] "; ожидалось "ALL, ANY, SOME, SELECT, FROM, WITH"
Syntax error in SQL statement "DELETE FROM ACCOUNTING  WHERE DATE_START =*[*] "; expected "ALL, ANY, SOME, SELECT, FROM, WITH"; SQL statement:
delete from ACCOUNTING  where DATE_START =* [42001-194]
2017-03-29 21:42:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "DELETE FROM ACCOUNTING  WHERE DATE_START =ALL [*]"; ожидалось "("
Syntax error in SQL statement "DELETE FROM ACCOUNTING  WHERE DATE_START =ALL [*]"; expected "("; SQL statement:
delete from ACCOUNTING  where DATE_START =all [42001-194]
2017-03-29 21:43:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "insert into ACCOUNTING (DATE_START) values ( PARSEDATETIME(''YYYY-MM-DD[*]',2000-00-00))"
Syntax error in SQL statement "insert into ACCOUNTING (DATE_START) values ( PARSEDATETIME(''YYYY-MM-DD[*]',2000-00-00))"; SQL statement:
insert into ACCOUNTING (DATE_START) values ( PARSEDATETIME(''YYYY-MM-DD',2000-00-00)) [42000-194]
2017-03-29 21:43:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка при разборе "2000"
Error parsing "2000"; SQL statement:
insert into ACCOUNTING (DATE_START) values ( PARSEDATETIME(2000-00-00,'YYYY-MM-DD')) [90014-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.util.DateTimeUtils.parseDateTime(DateTimeUtils.java:620)
	at org.h2.expression.Function.getValueWithArgs(Function.java:1513)
	at org.h2.expression.Function.getValue(Function.java:590)
	at org.h2.expression.Function.optimize(Function.java:2501)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.text.ParseException: Unparseable date: "2000"
	at java.text.DateFormat.parse(Unknown Source)
	at org.h2.util.DateTimeUtils.parseDateTime(DateTimeUtils.java:616)
	... 17 more
2017-03-29 22:45:26 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Artem 2/applicationDB.mv.db [1.4.194/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Artem 2/applicationDB.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at Application.getDBConnection(Application.java:39)
	at Application.main(Application.java:10)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Artem 2/applicationDB.mv.db [1.4.194/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Artem 2/applicationDB.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Artem 2/applicationDB.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 20 more
2017-03-29 23:21:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "[*]""INSERT INTO USER (NAME,PASS,SALT) VALUES ('','','')"
Syntax error in SQL statement "[*]""INSERT INTO USER (NAME,PASS,SALT) VALUES ('','','')"; SQL statement:
"INSERT INTO USER (NAME,PASS,SALT) VALUES ('','','') [42000-194]
2017-03-30 00:02:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_2" не найдено
Constraint "CONSTRAINT_INDEX_2" not found; SQL statement:
ALTER TABLE uSER DROP FOREIGN  KEY CONSTRAINT_INDEX_2 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:02:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_2" не найдено
Constraint "CONSTRAINT_INDEX_2" not found; SQL statement:
ALTER TABLE USER DROP FOREIGN KEY CONSTRAINT_INDEX_2 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:02:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE DROP FOREIGN KEY CONSTRAINT_INDEX_1 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:02:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1A" не найдено
Constraint "CONSTRAINT_INDEX_1A" not found; SQL statement:
ALTER TABLE RESOURCE DROP FOREIGN KEY CONSTRAINT_INDEX_1A [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:03:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "CONSTRAINT_INDEX_1A" не найден
Column "CONSTRAINT_INDEX_1A" not found; SQL statement:
ALTER TABLE RESOURCE DROP CONSTRAINT_INDEX_1A [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:676)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5629)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:03:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "CONSTRAINT_INDEX_1" не найден
Column "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE DROP CONSTRAINT_INDEX_1 [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:676)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5629)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:03:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "CONSTRAINT_INDEX_1A" не найден
Column "CONSTRAINT_INDEX_1A" not found; SQL statement:
ALTER TABLE RESOURCE DROP CONSTRAINT_INDEX_1A [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:676)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5629)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:04:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Индекс "CONSTRAINT_INDEX_1A" относится к ограничению "CONSTRAINT_1"
Index "CONSTRAINT_INDEX_1A" belongs to constraint "CONSTRAINT_1"; SQL statement:
ALTER TABLE RESOURCE DROP INDEX CONSTRAINT_INDEX_1A [90085-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.command.ddl.DropIndex.update(DropIndex.java:63)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:04:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE RESOURCE DROP FOREIGN KEY ([*]CONSTRAINT_INDEX_1A)"; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE RESOURCE DROP FOREIGN KEY ([*]CONSTRAINT_INDEX_1A)"; expected "identifier"; SQL statement:
ALTER TABLE RESOURCE DROP FOREIGN KEY (CONSTRAINT_INDEX_1A) [42001-194]
2017-03-30 00:04:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE RESOURCE DROP FOREIGN KEY ([*]'CONSTRAINT_INDEX_1A')"; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE RESOURCE DROP FOREIGN KEY ([*]'CONSTRAINT_INDEX_1A')"; expected "identifier"; SQL statement:
ALTER TABLE RESOURCE DROP FOREIGN KEY ('CONSTRAINT_INDEX_1A') [42001-194]
2017-03-30 00:05:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE RESOURCE DROP CONSTRAINT [*]'CONSTRAINT_INDEX_1A"
Syntax error in SQL statement "ALTER TABLE RESOURCE DROP CONSTRAINT [*]'CONSTRAINT_INDEX_1A"; SQL statement:
ALTER TABLE RESOURCE DROP CONSTRAINT 'CONSTRAINT_INDEX_1A [42000-194]
2017-03-30 00:05:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1A" не найдено
Constraint "CONSTRAINT_INDEX_1A" not found; SQL statement:
ALTER TABLE RESOURCE DROP CONSTRAINT CONSTRAINT_INDEX_1A [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:06:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1A" не найдено
Constraint "CONSTRAINT_INDEX_1A" not found; SQL statement:
ALTER TABLE RESOURCE  DROP CONSTRAINT CONSTRAINT_INDEX_1A [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:06:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "USER_ID" не найдено
Constraint "USER_ID" not found; SQL statement:
ALTER TABLE RESOURCE  DROP CONSTRAINT USER_ID [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:06:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "ID" не найдено
Constraint "ID" not found; SQL statement:
ALTER TABLE RESOURCE  DROP CONSTRAINT ID [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:07:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE RESOURCE  DROP CONSTRAINT ID 
ALTER[*] TABLE RESOURCE   DROP FOREIGN KEY ""CONSTRAINT_INDEX_1"" "
Syntax error in SQL statement "ALTER TABLE RESOURCE  DROP CONSTRAINT ID 
ALTER[*] TABLE RESOURCE   DROP FOREIGN KEY ""CONSTRAINT_INDEX_1"" "; SQL statement:
ALTER TABLE RESOURCE  DROP CONSTRAINT ID 
ALTER TABLE RESOURCE   DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [42000-194]
2017-03-30 00:07:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE   DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:07:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE   DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:07:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE   DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:07:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE   DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:07:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE   DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:07:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE   DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:07:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE   DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:07:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:08:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE RESOURCE,[*]USER  DROP FOREIGN KEY ""CONSTRAINT_INDEX_1"" "; ожидалось "., ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"
Syntax error in SQL statement "ALTER TABLE RESOURCE,[*]USER  DROP FOREIGN KEY ""CONSTRAINT_INDEX_1"" "; expected "., ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE RESOURCE,USER  DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [42001-194]
2017-03-30 00:08:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Схема "RESOURCE" не найдена
Schema "RESOURCE" not found; SQL statement:
ALTER TABLE RESOURCE.USER  DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [90079-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.getSchema(Parser.java:681)
	at org.h2.command.Parser.getSchema(Parser.java:687)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5521)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:08:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE RESOURCE USER[*]  DROP FOREIGN KEY ""CONSTRAINT_INDEX_1"" "; ожидалось "., ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"
Syntax error in SQL statement "ALTER TABLE RESOURCE USER[*]  DROP FOREIGN KEY ""CONSTRAINT_INDEX_1"" "; expected "., ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE RESOURCE USER  DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [42001-194]
2017-03-30 00:09:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE 'RESOURCE'[*] . 'USER'  DROP FOREIGN KEY ""CONSTRAINT_INDEX_1"" "; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE 'RESOURCE'[*] . 'USER'  DROP FOREIGN KEY ""CONSTRAINT_INDEX_1"" "; expected "identifier"; SQL statement:
ALTER TABLE 'RESOURCE' . 'USER'  DROP FOREIGN KEY `CONSTRAINT_INDEX_1` [42001-194]
2017-03-30 00:09:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT [*]"; ожидалось "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
SHOW CREATE TABLE RESOURCE [42001-194]
2017-03-30 00:10:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER DROP FOREIGN  KEY[*]"; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE USER DROP FOREIGN  KEY[*]"; expected "identifier"; SQL statement:
ALTER TABLE USER DROP FOREIGN  KEY [42001-194]
2017-03-30 00:10:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_2" не найдено
Constraint "CONSTRAINT_INDEX_2" not found; SQL statement:
ALTER TABLE USER DROP FOREIGN KEY CONSTRAINT_INDEX_2 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:11:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER DROP FOREIGN KEY=[*]CONSTRAINT_INDEX_2"; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE USER DROP FOREIGN KEY=[*]CONSTRAINT_INDEX_2"; expected "identifier"; SQL statement:
ALTER TABLE USER DROP FOREIGN KEY=CONSTRAINT_INDEX_2 [42001-194]
2017-03-30 00:12:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE  DROP CONSTRAINT CONSTRAINT_INDEX_1 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:13:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE  DROP CONSTRAINT CONSTRAINT_INDEX_1 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:13:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE  DROP CONSTRAINT CONSTRAINT_INDEX_1 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:13:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE  DROP CONSTRAINT CONSTRAINT_INDEX_1 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:13:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE  DROP CONSTRAINT CONSTRAINT_INDEX_1 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:13:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE  DROP FOREIGN KEY CONSTRAINT_INDEX_1 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:13:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "USER_ID" не найдено
Constraint "USER_ID" not found; SQL statement:
ALTER TABLE RESOURCE  DROP FOREIGN KEY USER_ID [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:13:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "USER_ID" не найдено
Constraint "USER_ID" not found; SQL statement:
ALTER TABLE RESOURCE  DROP FOREIGN KEY USER_ID [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:13:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT [*]"; ожидалось "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
SHOW CREATE TABLE RESOURCE [42001-194]
2017-03-30 00:14:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT [*]"; ожидалось "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
SHOW CREATE TABLE RESOURCE [42001-194]
2017-03-30 00:14:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT [*]"; ожидалось "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
SHOW CREATE TABLE RESOURCE [42001-194]
2017-03-30 00:14:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT [*]"; ожидалось "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
SHOW CREATE TABLE RESOURCE [42001-194]
2017-03-30 00:14:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT [*]"; ожидалось "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
SHOW CREATE TABLE RESOURCE [42001-194]
2017-03-30 00:14:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE IF EXISTS RESOURCE DROP CONSTRAINT PRIMARY[*] KEY"; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE IF EXISTS RESOURCE DROP CONSTRAINT PRIMARY[*] KEY"; expected "identifier"; SQL statement:
ALTER TABLE IF EXISTS RESOURCE DROP CONSTRAINT PRIMARY KEY [42001-194]
2017-03-30 00:15:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Индекс "PRIMARY_KEY_" не найден
Index "PRIMARY_KEY_" not found; SQL statement:
ALTER TABLE IF EXISTS RESOURCE DROP PRIMARY KEY [42112-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getPrimaryKey(Table.java:771)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5609)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:15:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE IF EXISTS RESOURCE DROP CONSTRAINT[*]"; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE IF EXISTS RESOURCE DROP CONSTRAINT[*]"; expected "identifier"; SQL statement:
ALTER TABLE IF EXISTS RESOURCE DROP CONSTRAINT [42001-194]
2017-03-30 00:15:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "CONSTRAINT_INDEX" не найден
Column "CONSTRAINT_INDEX" not found; SQL statement:
ALTER TABLE IF EXISTS RESOURCE DROP CONSTRAINT_INDEX [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:676)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5629)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:15:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "CONSTRAINT_INDEX_1" не найден
Column "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE IF EXISTS RESOURCE DROP CONSTRAINT_INDEX_1 [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:676)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5629)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:16:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE IF EXISTS RESOURCE DROP CONSTRAINT CONSTRAINT_INDEX_1 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:16:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE DROP CONSTRAINT CONSTRAINT_INDEX_1 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:16:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "CONSTRAINT_INDEX_1" не найдено
Constraint "CONSTRAINT_INDEX_1" not found; SQL statement:
ALTER TABLE RESOURCE DROP CONSTRAINT CONSTRAINT_INDEX_1 [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:17:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "USER_ID" не найдено
Constraint "USER_ID" not found; SQL statement:
ALTER TABLE RESOURCE DROP CONSTRAINT USER_ID [90057-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:20:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неизвестный тип данных: "USER_ID"
Unknown data type: "USER_ID"; SQL statement:
Alter table RESOURCE add int USER_ID [50004-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4144)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3994)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:5808)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5528)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:21:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE RESOURCE ADD COLLUMN INT USER_ID[*] "
Syntax error in SQL statement "ALTER TABLE RESOURCE ADD COLLUMN INT USER_ID[*] "; SQL statement:
Alter table RESOURCE add collumn int USER_ID [42000-194]
2017-03-30 00:21:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неизвестный тип данных: "USER_ID"
Unknown data type: "USER_ID"; SQL statement:
Alter table RESOURCE add COLUMN int USER_ID [50004-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4144)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3994)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:5808)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5528)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:21:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неизвестный тип данных: "ALTER"
Unknown data type: "ALTER"; SQL statement:
Alter table RESOURCE add COLUMN USER_ID
ALTER TABLE [ IF EXISTS ] tableName ADD [ COLUMN ]  [ IF NOT EXISTS ] columnDefinition | (   columnDefinition   [,...] )  
[   BEFORE | AFTER   columnName ] [50004-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4144)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3994)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:5808)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5528)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:22:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неизвестный тип данных: 
Unknown data type: ; SQL statement:
Alter table RESOURCE add COLUMN USER_ID [50004-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4144)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3994)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:5808)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5528)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:22:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неизвестный тип данных: "USER_ID"
Unknown data type: "USER_ID"; SQL statement:
Alter table RESOURCE add COLUMN INT USER_ID [50004-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4144)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3994)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:5808)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5528)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-30 00:24:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "ALTER TABLE USER ADD PRIMARY KEY ID[*] "; ожидалось "HASH, ("
Syntax error in SQL statement "ALTER TABLE USER ADD PRIMARY KEY ID[*] "; expected "HASH, ("; SQL statement:
Alter table USER add primary key id [42001-194]
2017-03-30 00:27:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "LOGIN" не найден
Column "LOGIN" not found [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3146)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3234)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:308)
	at Application.main(Application.java:53)
